### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jmuth** [jmuth/parliament-viz.ch#1]
# TODO list on the fly:

#### Visualization
- [x] fix this blocked points problem
- [x] put the search field above the person card, not above clustering option (question of taste, no obligation)
- [x] unselect point by clicking out of scope
- [x] make the color/cluster selection a drop-down menu (again: question of taste, dunno if it's really better or not)
- [x] clear instruction of use on the top, viz is clear enough and self-explained
- [x] color of ages in "one scale" (e.g. form bright blue to dark blue) to improve understanding
#### Activity field:
- [x] interventions start and and date matching real date (not first and last intervention)
- [x] filter interventions to keep the "long" ones? (no intermediate president speech)
- [ ] add number of time reporter? 
- [ ] add the percentage of participating votation per year, on 100% (double y-axis: #intervention and % vote participation)
#### Interest field:
- [ ] Add number of **approved** initiatives (maybe two colors on histogram, where sum of both make the heigh of it)
#### Credit
- [x] Add logo
- [x] Add creator
- [x] Add cours information
- [x] Add GitHub link
- [x] Eventually add acknowledgements?
#### Life
- [x] Sex
- [x] Drugs
- [ ] Rock'n'Roll
